initial commit
aws-quickstart/quickstart-uipath-automation-suite pull request #5
Opened 2022-08-05 22:28 UTC by sshvans

init commit*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-07 16:56 UTC, troy-ameigh submitted a review, later dismissed

2022-08-11 06:08 UTC, andrew-glenn requested changes
Please remove documentation from `develop`, so that docs and code are mutually exclusive.

2022-08-16 15:13 UTC, troy-ameigh approved these changes

2022-08-22 22:21 UTC, andrew-glenn approved these changes

2022-08-22 22:21 UTC, merged